#  Dutch translation to the english one for the API
country_translation = {
    "Afghanistan": "Afghanistan",
    "Albanië": "Albania",
    "Algerije": "Algeria",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Argentinië": "Argentina",
    "Armenië": "Armenia",
    "Australië": "Australia",
    "Oostenrijk": "Austria",
    "Azerbeidzjan": "Azerbaijan",
    "Bahama's": "Bahamas",
    "Bahrein": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "België": "Belgium",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bhutan": "Bhutan",
    "Bolivia": "Bolivia",
    "Bosnië en Herzegovina": "Bosnia and Herzegovina",
    "Botswana": "Botswana",
    "Brazilië": "Brazil",
    "Brunei": "Brunei",
    "Bulgarije": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cambodja": "Cambodia",
    "Kameroen": "Cameroon",
    "Canada": "Canada",
    "Kaapverdië": "Cape Verde",
    "Centraal-Afrikaanse Republiek": "Central African Republic",
    "Chili": "Chile",
    "China": "China",
    "Colombia": "Colombia",
    "Comoren": "Comoros",
    "Congo (Brazzaville)": "Congo (Brazzaville)",
    "Congo (Kinshasa)": "Congo (Kinshasa)",
    "Costa Rica": "Costa Rica",
    "Kroatië": "Croatia",
    "Cuba": "Cuba",
    "Cyprus": "Cyprus",
    "Tsjechië": "Czech Republic",
    "Denemarken": "Denmark",
    "Djibouti": "Djibouti",
    "Dominica": "Dominica",
    "Dominicaanse Republiek": "Dominican Republic",
    "Ecuador": "Ecuador",
    "Egypte": "Egypt",
    "El Salvador": "El Salvador",
    "Equatoriaal-Guinea": "Equatorial Guinea",
    "Eritrea": "Eritrea",
    "Estland": "Estonia",
    "Eswatini": "Eswatini",
    "Ethiopië": "Ethiopia",
    "Fiji": "Fiji",
    "Finland": "Finland",
    "Frankrijk": "France",
    "Gabon": "Gabon",
    "Gambia": "Gambia",
    "Georgië": "Georgia",
    "Duitsland": "Germany",
    "Ghana": "Ghana",
    "Griekenland": "Greece",
    "Grenada": "Grenada",
    "Guatemala": "Guatemala",
    "Guinee": "Guinea",
    "Guinee-Bissau": "Guinea-Bissau",
    "Guyana": "Guyana",
    "Haïti": "Haiti",
    "Honduras": "Honduras",
    "Hongarije": "Hungary",
    "IJsland": "Iceland",
    "India": "India",
    "Indonesië": "Indonesia",
    "Iran": "Iran",
    "Irak": "Iraq",
    "Ierland": "Ireland",
    "Israël": "Israel",
    "Italië": "Italy",
    "Ivoorkust": "Ivory Coast",
    "Jamaica": "Jamaica",
    "Japan": "Japan",
    "Jordanië": "Jordan",
    "Kazachstan": "Kazakhstan",
    "Kenia": "Kenya",
    "Kiribati": "Kiribati",
    "Korea (Noord)": "North Korea",
    "Korea (Zuid)": "South Korea",
    "Koeweit": "Kuwait",
    "Kirgizië": "Kyrgyzstan",
    "Laos": "Laos",
    "Letland": "Latvia",
    "Libanon": "Lebanon",
    "Lesotho": "Lesotho",
    "Liberia": "Liberia",
    "Libië": "Libya",
    "Liechtenstein": "Liechtenstein",
    "Litouwen": "Lithuania",
    "Luxemburg": "Luxembourg",
    "Madagaskar": "Madagascar",
    "Malawi": "Malawi",
    "Maleisië": "Malaysia",
    "Maldiven": "Maldives",
    "Mali": "Mali",
    "Malta": "Malta",
    "Mauritanië": "Mauritania",
    "Mexico": "Mexico",
    "Moldavië": "Moldova",
    "Monaco": "Monaco",
    "Mongolië": "Mongolia",
    "Montenegro": "Montenegro",
    "Marokko": "Morocco",
    "Mozambique": "Mozambique",
    "Myanmar": "Myanmar",
    "Namibië": "Namibia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Nederland": "Netherlands",
    "Nieuw-Zeeland": "New Zealand",
    "Nicaragua": "Nicaragua",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "Noord-Macedonië": "North Macedonia",
    "Noorwegen": "Norway",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Panama": "Panama",
    "Papoea-Nieuw-Guinea": "Papua New Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Filipijnen": "Philippines",
    "Polen": "Poland",
    "Portugal": "Portugal",
    "Qatar": "Qatar",
    "Roemenië": "Romania",
    "Rusland": "Russia",
    "Rwanda": "Rwanda",
    "Saint Kitts en Nevis": "Saint Kitts and Nevis",
    "Saint Lucia": "Saint Lucia",
    "Saint Vincent en de Grenadines": "Saint Vincent and the Grenadines",
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "Sao Tomé en Principe": "Sao Tome and Principe",
    "Saoedi-Arabië": "Saudi Arabia",
    "Senegal": "Senegal",
    "Servië": "Serbia",
    "Seychellen": "Seychelles",
    "Sierra Leone": "Sierra Leone",
    "Singapore": "Singapore",
    "Slowakije": "Slovakia",
    "Slovenië": "Slovenia",
    "Salomonseilanden": "Solomon Islands",
    "Somalië": "Somalia",
    "Zuid-Afrika": "South Africa",
    "Spanje": "Spain",
    "Sri Lanka": "Sri Lanka",
    "Soedan": "Sudan",
    "Suriname": "Suriname",
    "Zweden": "Sweden",
    "Zwitserland": "Switzerland",
    "Syrië": "Syria",
    "Taiwan": "Taiwan",
    "Tadzjikistan": "Tajikistan",
    "Tanzania": "Tanzania",
    "Thailand": "Thailand",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad en Tobago": "Trinidad and Tobago",
    "Tunesië": "Tunisia",
    "Turkije": "Turkey",
    "Turkmenistan": "Turkmenistan",
    "Tuvalu": "Tuvalu",
    "Oeganda": "Uganda",
    "Oekraïne": "Ukraine",
    "Verenigde Arabische Emiraten": "United Arab Emirates",
    "Verenigd Koninkrijk": "United Kingdom",
    "Verenigde Staten": "United States",
    "Uruguay": "Uruguay",
    "Oezbekistan": "Uzbekistan",
    "Vanuatu": "Vanuatu",
    "Vaticaanstad": "Vatican City",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "Jemen": "Yemen",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe"
}


def translate_country_name(dutch_name):
    """Translates a Dutch country name to its English equivalent."""
    translated = None
    for dutch_key, english_value in country_translation.items():
        if dutch_key.lower() == dutch_name.lower():
            translated = english_value
    return translated
